spring:
  datasource:
    url: jdbc:postgresql://localhost:5532/postgres
    username: "${db.user}"
    password: "${db.password}"
  jpa:
    open-in-view: false
  mustache:
    expose-request-attributes: true
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: "${fb.id}"
            client-secret: "${fb.secret}"